backend:
  name: github
  repo: laithalfaleh/albaronlaith
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

locale: "ar"

collections:
  - name: "blog"
    label: "المقالات"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "التاريخ", name: "date", widget: "datetime"}
      - {label: "موجز", name: "summary", widget: "text", required: false}
      - {label: "المحتوى", name: "body", widget: "markdown"}
