backend:
  name: github
  repo: laithalfaleh/albaronlaith  # اسم المستودع بالضبط
  branch: main
  auth_scope: repo

publish_mode: editorial_workflow

media_folder: "images/uploads"     # مجلد رفع الصور داخل المستودع
public_folder: "/images/uploads"   # مسار الصور على الموقع

site_url: https://laithalfaleh.github.io/albaronlaith

collections:
  - name: "posts"
    label: "مقالات"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "التاريخ", name: "date", widget: "datetime" }
      - { label: "الصورة", name: "thumbnail", widget: "image" }
      - { label: "المحتوى", name: "body", widget: "markdown" }
