backend:
  name: github
  repo: laithalfaleh/albaronlaith
  branch: main
  app_id: "Ov23lihjskBvJs97vKRj"

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "المقالات"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "التاريخ", name: "date", widget: "datetime" }
      - { label: "الصورة", name: "thumbnail", widget: "image" }
      - { label: "المحتوى", name: "body", widget: "markdown" }
