backend:
  name: github
  repo: laithalfaleh/albaronlaith    # اسم مستودعك على GitHub
  branch: main                       # الفرع الرئيسي
  app_id: "Ov23lihjskBvJs97vKRj"    # Client ID من تطبيق GitHub OAuth

media_folder: "assets/images"       # مجلد رفع الصور في المستودع (مثلاً)
public_folder: "/assets/images"     # مسار الصور لعرضها في الموقع

collections:
  - name: "posts"                   # اسم المجموعة (مثلاً: مقالات المدونة)
    label: "المقالات"
    folder: "posts"                 # المجلد في المستودع لوضع ملفات المقالات
    create: true                   # تفعيل إنشاء مقالات جديدة من لوحة الإدارة
    slug: "{{slug}}"               # عنوان URL للمقالة يُولد تلقائياً
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "التاريخ", name: "date", widget: "datetime" }
      - { label: "الصورة", name: "thumbnail", widget: "image" }
      - { label: "المحتوى", name: "body", widget: "markdown" }
