backend:
  name: github
  repo: laithalfaleh/albaronlaith
  branch: main
  base_url: https://decap-cms-auth.netlify.app
  app_id: "1280815"

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "المقالات"
    folder: "data"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "الصورة", name: "image", widget: "image" }
      - { label: "الملخص", name: "excerpt", widget: "text" }
      - { label: "المحتوى", name: "content", widget: "markdown" }
